### ISSUE TITLE
default_program(27): error: extra text after expected end of number    

### ISSUE THREAD

**Issue by jack-gits** [pytorch/serve#2728]
### 🐛 Describe the bug

After upgrade to 0.9.0, the previous model raise an exception as below

### Error logs

Backend received inference at: 1697908327
Invoking custom service failed.
Traceback (most recent call last):
  File "/home/venv/lib/python3.9/site-packages/ts/service.py", line 134, in predict
    ret = self._entry_point(input_batch, self.context)
  File "/home/venv/lib/python3.9/site-packages/ts/torch_handler/base_handler.py", line 358, in handle
    output = self.inference(data_preprocess)
  File "/home/model-server/tmp/models/2ee0edf1b19240159b1e15241ce4a498/inference-handler.py", line 58, in inference
    results = self.model(input_ids=input_ids,
  File "/home/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
RuntimeError: default_program(24): error: extra text after expected end of number
           aten_mul[(long long)(threadIdx.x) + 512ll * (long long)(blockIdx.x)] = v * -3.402823466385289e+38.f;
                          ^
 default_program(27): error: extra text after expected end of number
     aten_add[(long long)(threadIdx.x) + 512ll * (long long)(blockIdx.x)] = v_1 / 8.f + v_2 * -3.402823466385289e+38.f;
                          ^
 2 errors detected in the compilation of "default_program".
 
 nvrtc compilation failed: 
 
 #define NAN __int_as_float(0x7fffffff)
 #define POS_INFINITY __int_as_float(0x7f800000)
 #define NEG_INFINITY __int_as_float(0xff800000)
 
 
 template<typename T>
 __device__ T maximum(T a, T b) {
   return isnan(a) ? a : (a > b ? a : b);
 }
 
 template<typename T>
 __device__ T minimum(T a, T b) {
   return isnan(a) ? a : (a < b ? a : b);
 }
 
 extern "C" __global__
 void fused_mul_div_add(float* tattention_scores_2, float* tv_, float* aten_add, float* aten_mul) {
 {
 if (blockIdx.x<1ll ? 1 : 0) {
 if ((long long)(threadIdx.x) + 512ll * (long long)(blockIdx.x)<160ll ? 1 : 0) {
 if (blockIdx.x<1ll ? 1 : 0) {
         float v = __ldg(tv_ + (long long)(threadIdx.x) + 512ll * (long long)(blockIdx.x));
         aten_mul[(long long)(threadIdx.x) + 512ll * (long long)(blockIdx.x)] = v * -3.402823466385289e+38.f;
       }    }  }  float v_1 = __ldg(tattention_scores_2 + (long long)(threadIdx.x) + 512ll * (long long)(blockIdx.x));
   float v_2 = __ldg(tv_ + ((long long)(threadIdx.x) + 512ll * (long long)(blockIdx.x)) % 160ll);
   aten_add[(long long)(threadIdx.x) + 512ll * (long long)(blockIdx.x)] = v_1 / 8.f + v_2 * -3.402823466385289e+38.f;
 }
 }

### Installation instructions

torch version: release 0.9.0

### Model Packaing

torch version: release 0.9.0

### Versions

torch version: release 0.9.0

### Repro instructions

torch version: release 0.9.0

**Comment by msaroufim** [comment]
Do you have a minimal version and are you using cuda 12? An nvrtc compilation error is very unlikely to be a torchserve issue

**Comment by jack-gits** [comment]
yes using cuda 12.3 and torch 2.1.0

**Comment by jack-gits** [comment]
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Fri_Sep__8_19:17:24_PDT_2023
Cuda compilation tools, release 12.3, V12.3.52
Build cuda_12.3.r12.3/compiler.33281558_0

**Comment by jack-gits** [comment]
![image](https://github.com/pytorch/serve/assets/30545972/6dbdd1d3-20c0-43a5-b6e7-42dd7773c784)

**Comment by jack-gits** [comment]
is it a defect? @msaroufim

**Comment by msaroufim** [comment]
Are you using torchscript by any chance? some people have made a similar complaint in pytorch https://github.com/pytorch/pytorch/issues?q=is%3Aissue+is%3Aopen+error%3A+extra+text+after+expected+end+of+number

Problem is torchscript is on maintenance mode and so any bug is unlikely to get fixed, right now we're recommending users move to either `torch.compile()` and for those with very special needs `torch.jit.script()`
