### PR TITLE
Fixed install_from_src failure

### LINKED ISSUE #796: Install from source not working
Install from source is not working on a brand new ubuntu 18.04 machine.

Steps to reproduce:

1. Install openjdk
2. Install python 3.7
3. Run python ./scripts/install_from_src.py
```
Traceback (most recent call last):
  File "./scripts/install_from_src.py", line 10, in <module>
    from scripts import tsutils as ts
ImportError: cannot import name 'tsutils' from 'scripts' (/home/ubuntu/anaconda3/lib/python3.7/site-packages/scripts/__init__.py)
```

### PR DESCRIPTION
**Pull request by dhaniram-kshirsagar**
## Description

**NOTE - Apart from fixing the install dependency issue for manual installation. I had to rename the `script` package to `ts_script` to fix conflict with anaconda related `script` package!!**

Fixes #796 #797 

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Feature/Issue validation/testing

Please describe the tests [UT/IT] that you ran to verify your changes and relevent result summary. Provide instructions so it can be reproduced. 
Please also list any relevant details for your test configuration.

- Tested manually and via codebuild[AWS]
- Logs for manual testing of `python ts_scripts/install_from_src.py
[install_from_src.log.txt](https://github.com/pytorch/serve/files/5592454/install_from_src.log.txt)
- install_from_src.py - logs from gpu machine
[install_from_src_gpu.txt](https://github.com/pytorch/serve/files/5592721/install_from_src_gpu.txt)

## Checklist:

- [ ] Have you added tests that prove your fix is effective or that this feature works?
- [ ] New and existing unit tests pass locally with these changes?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [X] Have you made corresponding changes to the documentation?

### CODE REVIEW

**Comment by dhaniram-kshirsagar** [comment]
Looks like recent check-in for torchserve-sdk related test cases have broken torchserve_sanity.py on windows native.
@dhanainme Can we trigger windows ci as well so that this is taken care.

**Review by maaquib — APPROVED** [review]

**Review by dhanainme — APPROVED** [review]
