### ISSUE TITLE
misaligned argument between `args.disable_token` and `--disable_token-auth` in llm_launcher.py

### ISSUE THREAD

**Issue by jinyichao** [pytorch/serve#3229]
### 🐛 Describe the bug

There is a mis-alignment between `args.disable_token` (line 102) and `--disable_token-auth` (line 137) in llm_launcher.py, resulting errors when following the https://github.com/pytorch/serve/blob/master/docs/llm_deployment.md

### Error logs

Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/venv/lib/python3.9/site-packages/ts/llm_launcher.py", line 165, in <module>
    main(args)
  File "/home/venv/lib/python3.9/site-packages/ts/llm_launcher.py", line 102, in main
    disable_token=args.disable_token,
AttributeError: 'Namespace' object has no attribute 'disable_token'

### Installation instructions

docker build . -f docker/Dockerfile.llm -t ts/llm

### Model Packaging

not related

### Versions

Torchserve branch: 

torchserve==0.11.0
torch-model-archiver==0.11.0

Python version: 3.10 (64-bit runtime)
Python executable: /usr/bin/python3

Versions of relevant python libraries:
numpy==2.0.0
pillow==10.4.0
psutil==6.0.0
requests==2.25.1
torch==2.3.1
torch-model-archiver==0.11.0
torch-workflow-archiver==0.2.13
torchserve==0.11.0
torchvision==0.18.1
wheel==0.37.1
torch==2.3.1
**Warning: torchtext not present ..
torchvision==0.18.1
**Warning: torchaudio not present ..

OS: Ubuntu 22.04.4 LTS
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: N/A
CMake version: version 3.22.1

Is CUDA available: Yes
CUDA runtime version: N/A
GPU models and configuration: 
GPU 0: GRID A100D-2-20C
  MIG 2g.20gb     Device  0:
Nvidia driver version: 550.54.15

### Repro instructions

docker build . -f docker/Dockerfile.llm -t ts/llm
export token=<HUGGINGFACE_HUB_TOKEN>
docker run --rm -ti --gpus all -e HUGGING_FACE_HUB_TOKEN=$token -p 8080:8080 -v data:/data ts/llm --model_id meta-llama/Meta-Llama-3-8B-Instruct --disable_token

### Possible Solution

change line 137 from `--disable_token-auth` back into `--disable_token`

**Comment by mreso** [comment]
Thanks for giving llm deployment a try!

Seems like this was broken with #3224 
Created a PR to fix #3230 

Let us know if you find any other issues!

**Comment by jinyichao** [comment]
Thank you @mreso for the quick fix! It works well now! Let me close this issue.
